logging:
  config: classpath:logback-${spring.profiles.active}.xml

spring: 
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: false
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true
 
---     
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
      username: kostajava
      password: 1234
  thymeleaf:
    cache: false
  resources:
    cache:
      period: 0    

---      
spring:
  profiles: production
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      username: kostajava
      password: 1234
